# Generated by Django 6.0.6 on 2026-06-13 06:38

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to=reports.models.evidence_upload_path),
        ),
    ]
